version: '2'
services:
    jhipdash-app:
        image: jhipdash
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipdash-postgresql:5432/jhipdash
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipdash-postgresql:
        extends:
            file: postgresql.yml
            service: jhipdash-postgresql
