version: '2'
services:
    jhipdash-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipdash/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipdash
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
